# Generated by Django 5.2.6 on 2025-09-17 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_full_name_alter_user_token'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_blocking_user', 'Can blocking user'), ('can_disabling_mailings', 'Disabling mailings')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
