# Generated by Django 5.2.6 on 2025-09-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_blocking_user', 'Can blocking user'), ('can_list_user_view', 'Can list user view')], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
