# Generated by Django 5.2.6 on 2025-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Введите электронную почту', max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ф.И.О.')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
    ]
