# Generated by Django 5.2.6 on 2025-09-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front_mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Тема письма', max_length=200, verbose_name='Тема письма')),
                ('letter', models.TextField(verbose_name='Письмо')),
            ],
        ),
    ]
