# Generated by Django 5.2.6 on 2025-09-14 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='first_shipment',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='last_shipment',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
