# Generated by Django 5.2.6 on 2025-09-17 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_mailing_author_recipient_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('can_disabling_mailings', 'Disabling mailings'), ('can_mailing_static_view', 'Can mailing static view')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
